# Generated by Django 4.1.7 on 2023-04-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_count_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='test',
            field=models.BooleanField(default=True),
        ),
    ]
