# Generated by Django 4.1.7 on 2023-04-03 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_category_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='test',
        ),
    ]
